---
title: "0-dev_setup"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../"))

ls_corc <- function(pattern) {ls(pattern = pattern, name = "package:CoRC", all.names = TRUE)}

reset_copasi <- function() {
  if (exists("unloadAllModels")) unloadAllModels()
  rm(list = ls(envir = .GlobalEnv) %>% .[!(. %in% c("reset_copasi", "ls_corc", "inspect"))], envir = .GlobalEnv)
  
  devtools::load_all(reset = FALSE)
  
  setCurrentModel(
    loadExamples()[[4]]
  )
  
  assign("datamodel", getCurrentModel(), envir = .GlobalEnv)
  setTimeCourseSettings(duration = 100, dt = 1)
}

inspect <- function(object) {
  if (is.function(object)) {
     funtext <- object %>% environment() %>% .$f %>% format()
     cfun <- funtext %>% stringr::str_match("^\\s*(\\.Call\\(\"(\\w+).*\\))$") %>% na.omit()
     cat(
       cfun[,3] %>% stringr::str_sub(8),
       funtext[1] %>% stringr::str_sub(11, -2),
       "",
       cfun[,3],
       cfun[,2],
       sep = "\n"
     )
  } else {
    classes <- is(object)
    
    functions <-
      classes %>%
      map(safely(getMethod, quiet = TRUE), f = "$") %>%
      transpose() %>%
      .$result
    
    to_keep <- !map_lgl(functions, is_null)
    
    classes <- classes[to_keep]
    functions <- functions[to_keep]
    
    functions %>%
      map(~ {
        funtext <- format(.x)
        liststart <- stringr::str_which(funtext, "accessorFuns =")
        listend <- stringr::str_which(funtext %>% tail(-liststart + 1L), "\\)$")
        listtext <- paste0(funtext[seq(liststart, listend[1] + liststart - 1L)], collapse = "\n")
  
        parse(text = paste0(listtext, "\n", "names(accessorFuns)")) %>% eval()
      }) %>%
      set_names(classes) %>%
      {.[length(.):1L]}
  }
}

```

# Document the Package

```{r}
devtools::document()
```

# Install the Package

```{r}
devtools::install()
```

# Load the Package

```{r}
library(CoRC)

reset_copasi()
```

# Load Development Environment

```{r}
library(purrr)
library(ggplot2)
.data <- rlang::.data
library(assertthat)

reset_copasi()
```

# Reset Copasi

```{r}
reset_copasi()
```

# Tests

```{r}

```
