---
title: "0-dev_setup"
output: html_notebook
---

This file contains various helpers for the development environment.
Use this to load the development environment and frequently run reset_copasi() to load code changes.

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
# reset_copasi(), ls_corc(pattern), inspect(object)
source("dev_tools.R", echo = FALSE)
current_example = 3L
```

# Document the Package

```{r, include=FALSE}
devtools::document()
pkgdown::build_reference()
```

# Install the Package

```{r, include=FALSE}
devtools::install()
```

# Load the Package

```{r, include=FALSE}
library(CoRC)
```

# Load Development Environment

```{r, include=FALSE}
library(assertthat)
library(purrr)
library(ggplot2)
.data <- rlang::.data

reset_copasi()
```

# Reset COPASI

```{r, include=FALSE}
reset_copasi()
```

# Tests

```{r}
c_task <- as(c_datamodel$getTask("Optimization"), "_p_COptTask")
c_problem <- as(c_task$getProblem(), "_p_COptProblem")

c_constlist <- c_problem$getConstraintList()
c_optitem <- c_constlist %>% get_sv() %>% .[[1]]
c_optitem$getObjectDisplayName()

c_optitem$getObject() %>% get_cn()
```
