---
title: "0-dev_setup"
output: html_notebook
---

This file contains various helpers for the development environment.
Use this to load the development environment and frequently run reset_copasi() to load code changes.

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
Sys.setenv(COPASI_LIB_PATH = normalizePath(file.path("..", "libs", .Platform$r_arch, paste0("COPASI", .Platform$dynlib.ext))))

# reset_copasi(), ls_corc(pattern), inspect(object)
source("dev_tools.R", echo = FALSE)
current_example = 3L
```

# Document the Package

```{r, include=FALSE}
devtools::document()
pkgdown::build_reference()
``` 

# Check the Package

```{r, include=FALSE}
devtools::test()
```
```{r, include=FALSE}
devtools::check(check_dir = "../CoRC.Rcheck")
```

# Build the Package

```{r, include=FALSE}
devtools::build()
```

# Install the Package

```{r, include=FALSE}
devtools::install()
```

# Load the Package

```{r, include=FALSE}
library(CoRC)
```

# Load Development Environment

```{r, include=FALSE}
library(assertthat)
library(purrr)
library(ggplot2)

reset_copasi()
```

# Reset COPASI

```{r, include=FALSE}
reset_copasi()
```

# Tests

```{r}

```
