---
title: "Model Building"
author: "Jonas Förster & Jürgen Pahle"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Model Building}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 6,
  out.width = "100%",
  error = TRUE,
  warning = TRUE,
  message = FALSE
)
set.seed(1)
```

## Initial Setup

```{r setup}
library(tidyverse)
library(CoRC)
```

## Quick Model Building

Building a quick Michaelis-Menten reaction using Copasis automatisms.
Working with reaction schemes automatically creates required entities the same way the GUI does.

```{r}
newModel()

newReaction("a = b", fun = "Reversible Michaelis-Menten")

getSpecies()
getReactions()
getParameters()

unloadModel()
```

## More Detail

Getting more detail in can be helpful.

```{r}
newModel()

subs_quant <- newGlobalQuantity("substrate concentration", initial.value = 10)
subs_value <- quantity(subs_quant, reference = "Value")

newSpecies("a", type = "assignment", expression = subs_value)
newReaction("a = b", fun = "Reversible Michaelis-Menten")

getGlobalQuantities()
getSpecies()
getReactions()
getParameters()

runTC(1000) %>% autoplot()

unloadModel()
```

# Defining Reaction Kinetics Manually

```{r}
newModel()

newCompartment("compartment")
newSpecies("a", type = "fixed", initial.concentration = 10)
newSpecies("b")
fun <-
  newKineticFunction(
    "manual MM",
    "((Vf * substrate) / Kms - Vr * product / Kmp) / (1 + substrate / Kms + product / Kms)",
    parameters = c(substrate = "substrate", product = "product")
  )
newReaction("a = b", fun = fun)

runTC(1000) %>% autoplot()

unloadModel()
```

# Quantities as Proxy for Time Course Output

```{r}
newModel()

subs_quant <- newGlobalQuantity("substrate concentration", initial.value = 10)
subs_value <- quantity(subs_quant, reference = "Value")

newSpecies("a", type = "assignment", expression = subs_value)
newReaction("a = b", fun = "Reversible Michaelis-Menten")

runTC(1000) %>% autoplot()

newGlobalQuantity("reaction rate", type = "assignment", expression = reaction("a = b", reference = "Flux"))

runTC(1000) %>% autoplot()

unloadModel()
```