FROM alpine

RUN apk add --no-cache \
	bash \
	build-base \
	cmake \
	curl \
	R-dev \
	swig
	
RUN mkdir corc \
	&& cd corc \
	&& curl -L https://github.com/jpahle/CoRC/archive/master.tar.gz | tar -xz --strip 1
	
RUN mkdir copasi-dependencies \
	&& cd copasi-dependencies \
	&& curl -L https://github.com/copasi/copasi-dependencies/archive/master.tar.gz | tar -xz --strip 1

RUN mkdir COPASI \
	&& cd COPASI \
	&& curl -L https://github.com/copasi/COPASI/archive/develop.tar.gz | tar -xz --strip 1

RUN cd copasi-dependencies/ \
	&& BUILD_DIR=${PWD}/tmp_linux_x64 \
		INSTALL_DIR=${PWD}/bin_linux_x64 \
		./createLinux.sh

RUN apk add --no-cache \
	R
	
RUN mkdir corc_linux_x64/ \
	&& cd corc_linux_x64/ \
	&& cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DBUILD_GUI=OFF \
		-DBUILD_SE=OFF \
		-DENABLE_R=ON \
		-DR_USE_DYNAMIC_LOOKUP=ON \
		-DCOPASI_DEPENDENCY_DIR=../copasi-dependencies/bin_linux_x64/ \
		../COPASI/ \
	&& make binding_r_lib
